name: tests

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conan-current-page: [1, 2, 3, 4, 5, 6]
        conan-total-pages: [6]
        conan-cpu-count: [2]
        os: [ubuntu-20.04]
        include:
          - os: windows-2019
            conan-current-page: 1
            conan-total-pages: 1
            conan-cpu-count: 1
          - os: macos-11.0
            conan-current-page: 1
            conan-total-pages: 1
            conan-cpu-count: 3
    runs-on: ${{ matrix.os }}
    env:
      CONAN_REQUEST_TIMEOUT: 300
      CONAN_CPU_COUNT: ${{ matrix.conan-cpu-count }}
      CONAN_TOTAL_PAGES: ${{ matrix.conan-total-pages }}
      CONAN_CURRENT_PAGE: ${{ matrix.conan-current-page }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Install dependencies
        run: python -m pip install -U conan conan_package_tools

      - name: Install Ubuntu compilers
        if: matrix.os == 'ubuntu-20.04'
        run: |
          echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main" | sudo tee /etc/apt/sources.list.d/llvm-11.list
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y clang-6.0 clang-7 clang-11 libc++-11-dev libc++-11-dev libc++abi-11-dev

      - name: Build
        run: python .github/build.py

  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Build documentation
        run: doxygen

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
