name: tests

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        conan-current-page: [1, 2, 3, 4]
        conan-total-pages: [4]
        os: [ubuntu-20.04]
        include:
          - os: windows-2019
            conan-current-page: 1
            conan-total-pages: 1
          - os: macos-11.0
            conan-current-page: 1
            conan-total-pages: 1
    runs-on: ${{ matrix.os }}
    env:
      UNITY_BATCH: 10
      CONAN_REQUEST_TIMEOUT: 300
      CONAN_TOTAL_PAGES: ${{ matrix.conan-total-pages }}
      CONAN_CURRENT_PAGE: ${{ matrix.conan-current-page }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1

      - name: Cache conan data
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: ${{ matrix.os }}-build-${{ matrix.conan-current-page }}-${{ matrix.conan-total-pages }}-${{ hashFiles('**/conanfile.py') }}-${{ hashFiles('**/build.py') }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ matrix.conan-current-page }}-${{ matrix.conan-total-pages }}

      - name: Install dependencies
        run: python -m pip install -U conan conan_package_tools

      - name: Install compilers
        if: matrix.os == 'ubuntu-20.04'
        run: sudo apt-get install -y clang-6.0 clang-7

      - name: Build
        run: python .github/build.py

  docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install doxygen
        run: sudo apt-get install -y doxygen

      - name: Build documentation
        run: doxygen

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
